### ISSUE TITLE
seperate core framework and own theme

### ISSUE THREAD

**Issue by bangive** [gae-init/gae-init#334]
I see gae-boilerplate has this function. It won't overwrite my code when there is some change from the framework.

**Comment by lipis** [comment]
Some things could be possibly more isolated like `util.py` but in general this is kind of by design. While I'm trying hard to minimise the conflicts, as you might understand this is impossible. This project is not exactly a library that you can simply include, but more like an unfinished product with a core functionality there :) What I can suggest is, if you have an active app that you started with gae-init.. keep watching for changes and merge more often if you want to keep up..
