### ISSUE TITLE
Integrating AngularJS

### ISSUE THREAD

**Issue by dhstack** [gae-init/gae-init#345]
In the related discussion, #268, prior to v 2.0 landing (w/ REST API), there were some hints at how to do this, but no clear outline. Given the new API, what is the best way to integrate angular into gae-init?

Specifically, I'm considering using this [wrapbootstrap theme](https://wrapbootstrap.com/theme/angle-bootstrap-admin-app-angularjs-WB04HF123).

**Comment by topless** [comment]
Since I remember my self I work on porting it to angular, but still work in progress.
You can get some inspiration from [angular](https://github.com/topless/gae-init/tree/angular) branch of my fork. There are several changes especially in the build system. I am working on a side project at the moment so there will be updates there for sure.

**Comment by dhstack** [comment]
Thanks, topless. I'll take a look

**Comment by jaxon** [comment]
I'm also working on integrating Angular into gae-init.

**Comment by jaxon** [comment]
I found a repo called [GAE Angular Material Starter](https://github.com/madvas/gae-angular-material-starter)  which uses  [gae-init](https://github.com/gae-init/gae-init) and [MEANJS](https://github.com/meanjs) ([Angular](https://github.com/angular)). 

Looks promising.

**Comment by bangive** [comment]
i'm also like this intergation very much. Hope to see it soon.

**Comment by bangive** [comment]
@jaxon  GAE Angular Material Starter looks great!

**Comment by lipis** [comment]
Closing this one.. since there are no plans in the near future to have that in the core
