### ISSUE TITLE
Strange code in user.less

### ISSUE THREAD

**Issue by gmist** [gae-init/gae-init#378]
I am a bit do not understand purpose of [line #3](https://github.com/gae-init/gae-init/blob/master/main/static/src/style/user.less#L3). Can anyone explain it to me?

**Comment by lipis** [comment]
Nothing.. it was me trying to be a designer.. cause the name in the user (because of the image there as well) it looked a bit smaller..  than the usual.. by adding that it's bold and a bit bigger :)

![screen shot 2015-06-05 at 01 35 24](https://cloud.githubusercontent.com/assets/125676/7996685/69cd640e-0b23-11e5-916a-5e29c3674c64.png)

**Comment by gmist** [comment]
Ah, I got it. Thanks!

**Comment by lipis** [comment]
and I guess you already found this: https://github.com/twbs/bootstrap/blob/master/less/type.less#L9-L52

**Comment by gmist** [comment]
Yeah, I just missed this mixins.
