### ISSUE TITLE
Storing Permission roles from @auth.permission_required

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#381]
I am trying to store the permission roles which are established using the decorator @auth.permission_required in an NDB database as a model, as well as being able to add and delete roles and users from roles. Is this something which is possible, or will I need to rewrite the decorator?

Many thanks!

**Comment by lipis** [comment]
There is a lot of _magic_ in that decorator made by mr. @joernhees.. so here is how it works:

just add the decorator `@auth.permission_required('moderator')` in any handler you want.. and you'll be able to add/remove that permission from any user :D Keep adding as many as you want..

**Comment by joernhees** [comment]
yupp, the decorator automagically registers whatever string you use as a `permission` in [`@auth.permission_required(permission)`](https://github.com/gae-init/gae-init/blob/master/main/auth/auth.py#L143)

During runtime all the `permission`s you used during decoration end up in the [UserUpdateForm](https://github.com/gae-init/gae-init/blob/master/main/control/user.py#L75) so that you can actually grant the `permission` to a user (which saves it in the `model.User.permissions`-multi-string-field).

That way you don't need any other steps than decorating the endpoints with the `permission` to be able to grant that `permission` to users via the UserForm.

If for whatever reason you want to user further permissions that you don't want to decorate to things (yet), you can either extend the [`_permission_choices`](https://github.com/gae-init/gae-init/blob/master/main/control/user.py#L67) or even easier just use a fake call of the decorator like this:

```python
auth.permission_required('some_future_permission')(lambda: None)
```

Also see the docs: http://docs.gae-init.appspot.com/reference/#@auth.permission_required

**Comment by charleswson** [comment]
Thank you both very much! I didn't realise that the decorator was that powerful! :+1:

**Comment by lipis** [comment]
![queen_a_kind_of_magic](https://cloud.githubusercontent.com/assets/125676/8232527/3128934c-15d9-11e5-9e89-1e16619525f0.png)

**Comment by gmist** [comment]
![shia-magic](https://cloud.githubusercontent.com/assets/47926/8232569/88e04332-15d9-11e5-8f65-b95330ce8f7e.gif)

**Comment by charleswson** [comment]
Indeed it is! (And it's a great song as well) 😃

**Comment by lipis** [comment]
LOL :) Much better than mine :)

**Comment by topless** [comment]
@gmist you nailed it ... for a period of time I thought that text was your only output :)
