### ISSUE TITLE
oauth2?

### ISSUE THREAD

**Issue by aws623** [gae-init/gae-init#419]
best way to use oauth2 authentication for deployment to just add it to the build.coffee options string?

**Comment by topless** [comment]
If I get your question right, you want to authenticate towards google when you try to `gulp deploy`.
You can run `gcloud auth login`, in order to authenticate and then this will be used for your deployment. If you want to authenticate as another user you can use the `--no_cookies` argument of dev_appserver.py. Run `gulp deploy --no_cookies` and will ask you to authenticate every time you deploy. Gulp deploy pipes all the arguments to `dev_appserver`.
