### ISSUE TITLE
Account conflict notification

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#421]
While I was reading through the source code, I found these lines:

https://github.com/gae-init/gae-init/blob/master/main/auth/auth.py#L404-L406

Under what circumstances would this error message be displayed, and is this likely to happen in production?

Many thanks! :smiley:

**Comment by lipis** [comment]
```
user_dbs, cursors = model.User.get_dbs(email=email, active=True, limit=2)
```

This will happen if the user that is trying to login using their email/password and that particular email belongs to at least 2 active users. Since there is no way to distinguish which one should be the right one, that's why the error message and the possible email notification.

In theory that should not happen.. but as long as humans involved you cannot trust this theory completely :)

**Comment by charleswson** [comment]
Thank you! Is there not a way to prohibit a user from using an email more than once when signing up?

**Comment by lipis** [comment]
I would say, don't worry about that one, that can only happen in some dodgy case where the user will change their email without verifying it and then login with another provider that uses that email an a new account will be created (instead of automagically merged).. everything will work fine until that user tries to login using email/password.

In any other case it should work without any conflict.

**Comment by charleswson** [comment]
Ah, I see the issue. Thank you very much! :smile:

**Comment by lipis** [comment]
You can always try all sort of different scenarios here if you like: https://gae-init.appspot.com/signin/ :) If you manage to break something.. we'll be happy to have it fixed :)

**Comment by charleswson** [comment]
Challenge accepted! :wink:
