### ISSUE TITLE
param and get_next_url

### ISSUE THREAD

**Issue by charleswson** [gae-init/gae-init#422]
I'm having some trouble understanding how the procedures param and get_next_url work. While I can see what they are used to do (from looking at where they are used), I can't follow the code's functionality (particularly how get_next_url is using param). Is anyone able to explain this?

**Comment by lipis** [comment]
http://docs.gae-init.appspot.com/reference/#util.param

**Comment by lipis** [comment]
`param` - In short in order to get some arguments from all sort of different requests (`json`, `form`, `args`) you need to get it from the right module. By using the param you basically don't care about it and you can use it in any sort of request. Think about it as a wrapper for `get` :) Plus it does some other smart things if you are going to provide a second param `cast`. For example if you know that you are expecting a boolean value for an argument `public` you can simply do that `public = util.param('public', bool)` or `stuff = util.param('stuff', list)` and you can provide a comma separated string that will be automatically transformed to a list, etc..

`get_next_url` - Used mainly when you are trying to login and you want to return to the same page. But could also be used in submit forms and more. In the beginning it was using the `referrer` but later on the more arguments were added. For example if the `&next=/profile/` is present it will go there. For example: https://gae-init.appspot.com/signin/?next=/profile/ you will go directly to the profile after a login.. :)


The docs are bit dated.. but hopefully one day they will be improved :) http://docs.gae-init.appspot.com/reference/#util.param

**Comment by charleswson** [comment]
Thank you so much for your support! I really appreciate it - willing to help in any way I can :smile:
