### ISSUE TITLE
Delete items - Help (Not gae-init specific)

### ISSUE THREAD

**Issue by dovy** [gae-init/gae-init#539]
Trying to link 3 models to do nested deleting. Have a little bit of an issue, so I was instructed to post here.

```python
@app.route('/plugin/<int:plugin_id>/delete/', methods=['POST'])
@auth.admin_required
def plugin_delete(plugin_id):
    print('Delete %s' % plugin_id)
    plugin_db = model.Plugin.get_by_id(plugin_id)
    if not plugin_db or plugin_db.user_key != auth.current_user_key():
        flask.flash('You do not own this plugin, delete failed.', category='danger')
        return flask.redirect(flask.url_for('plugin_list'))

    # Delete all versions, patches, and codes for this plugin
    print('Whaa?')
    version_dbs = plugin_db.get_version_dbs()[0]
    print('Grr')
    import pprint
    pprint.pprint(version_dbs)

    if version_dbs:
        print('what?!')
        for ver in version_dbs:
            print('Doh')
            print(ver)
            # patch_dbs = ver.get_patch_dbs()
            # print('word')
            # if patch_dbs:
            #     for patch in patch_dbs:
            #         print('word2')
            #         patch.key.delete()
            print('word3')
            v = model.Theme.get_by_id(ver.key.id())
            v.key.delete()
            print('Exit')
    print('word4')
    code_dbs = plugin_db.get_code_dbs()
    if code_dbs:
        for code in code_dbs:
            code.key.delete()
    # plugin_db.key.delete()
    flask.flash('Plugin deleted.', category='success')
    return flask.redirect(flask.url_for('plugin_list'))
```

As per the example, added helper functions to grab the nested models. Now I want to delete all of the linked IDs.

The issue I get, however, is:
AttributeError: 'NoneType' object has no attribute 'Version'

**Comment by lipis** [comment]
You have too many things going on there.. first of all delete the comments and start isolating things..

but overall in order to make it much better you should use the [`_pre_delete_hooks`](https://cloud.google.com/appengine/docs/python/ndb/modelclass#Model__pre_delete_hook), [`ndb.delete_multi`](https://cloud.google.com/appengine/docs/python/ndb/functions) and maybe some more [general stuff](https://cloud.google.com/appengine/docs/python/ndb/creating-entities).

Also since I know that you are using [magic](https://magic.gae-init.appspot.com) check the generated models if you have parent/child relationships.. like in [Issue Tracker](http://magic.gae-init.appspot.com/project/5798568036139008/)

```python
  @classmethod
  def _pre_delete_hook(cls, key):
    project_db = key.get()
    issue_keys, _null = project_db.get_issue_dbs(keys_only=True, limit=-1)
    ndb.delete_multi(issue_keys)
```

**Comment by lipis** [comment]
I'll assume that this is solved.. :)

**Comment by dovy** [comment]
Yup. ;)
