### ISSUE TITLE
Docs links don't work with HTTPS Everywhere users

### ISSUE THREAD

**Issue by arcticnacho** [gae-init/gae-init#555]
HTTPS Everywhere seems to redirect \*.appspot.com and \*.\*.appspot.com to HTTPS, but doesn't let you through at https://docs.gae-init.appspot.com (HSTS) - GAE versioning recognises https://docs-dot-gae-init.appspot.com and https://docs.gae-init.appspot.com to be pretty much the same, but with the latter the certificate is valid and it works over HTTPS. Perhaps change links to https://docs-dot-gae-init.appspot.com?

**Comment by lipis** [comment]
I'm aware of it.. but didn't want to change the links because the URL is not that pretty :)
<img width="650" alt="screen shot 2016-09-03 at 13 21 08" src="https://cloud.githubusercontent.com/assets/125676/18224544/516da04a-71d9-11e6-8087-b6e47b076b00.png">

Also the idea was that I will change the whole thing to http://docs.gae-init.com since Let's Encrypt gives free certificates now.. but kind of didn't follow up because every 3 months I have to update them and back then it wasn't that automatic.. maybe this winter I'll give it another shot and move everything to the new domain without the appspot :)

**Comment by arcticnacho** [comment]
Sure, that makes sense :)

**Comment by lipis** [comment]
Plus we need to update the contents.. :) One day.. Thanks for the report..
