### ISSUE TITLE
Authentication Office365

### ISSUE THREAD

**Issue by renierperez** [gae-init/gae-init#585]
Hello, I wanted to know if you plan to implement authentication Office365, thank you very much, your project is very interesting.

**Comment by topless** [comment]
@renierperez we already support Microsoft live as auth provider, if Office365 is a different one, we will have to add it to the list of providers under `main/auth/`, otherwise you have to just add your credentials on the page `/admin/auth/` under Microsoft, feel free to create a pull request with the new provider or create an issue with your request.

**Comment by renierperez** [comment]
@topless Office365 is a different, https://azure.microsoft.com/en-us/documentation/articles/active-directory-how-subscriptions-associated-directory/.  These examples detail the differences: 

1. https://github.com/OneBitSoftware/Office365-SharePoint-Python-Flask-Sample
2. https://github.com/OfficeDev/PnP/blob/497b0af411a75b5b6edf55e59e48c60f8b87c7b9/Samples/AzureAD.GroupMembership/readme.md

thanks for your answer.

**Comment by gmist** [comment]
In other words, you need Azure OAuth2 backend?

**Comment by renierperez** [comment]
That's right, I need Azure OAuth2 backend.
