### ISSUE TITLE
Shall we switch to exact latest versions for the dependencies?

### ISSUE THREAD

**Issue by lipis** [gae-init/gae-init#597]
With [Greenkeeper](https://greenkeeper.io/) we can have them all up to date.. WDYT?

- [package.json#L14-L41](https://github.com/gae-init/gae-init/blob/master/package.json#L14-L41)
- [bower.json#L4-L7](https://github.com/gae-init/gae-init/blob/master/bower.json#L4-L7)

**Comment by mdxs** [comment]
Being explicit about what is known to make gae-init work properly (thus: which exact versions are proven to work together) is a Good Thing (tm), but it does of course add a maintenance burden.

I'm not familiar with Greenkeeper, but if that takes the burden out... or reduces it, then great.

At the moment, I don't recall having seen a broken gae-init due to any incompatible package updates in the JavaScript based pipeline; but it can happen... according to Murphy it thus will happen.

**Comment by lipis** [comment]
Yeah.. maybe I'll do that..
