### ISSUE TITLE
creating a larger gae-init support ecosystem?

### ISSUE THREAD

**Issue by mroswell** [gae-init/gae-init#664]
My sense is that project this is a great starting point, but as a relative newcomer to flask and to the project, I keep finding myself needing additional support. It would be great to have two resources available:

1. A gae-init-user email list (or slack?) for communication about learning curve issues.

2. A collection of mentors who could participate in codementor.io or other paid (or volunteer)  online pair-mentoring. When I pay for support on codementor.io, two different mentors have suggested that I not use this project (in favor something that they say is simpler, but mostly it's just a choice that they feel more comfortable with). An issue that might take me days to figure out would be much easier to solve if there were a community of gae-init mentors who might be available for support. (i.e Why does my new Vue not work yet with gae-init, when it works perfectly well in my straight HTML/CSS/Vue project?)  The Vue question might lend itself to being an issue here (and I will post it), but other questions coming from a "help, where do, I start" perspective might be well-served to have a more expanded support ecosystem.

Perhaps two more resources, as well:

3. videos (I can do this if I ever get myself up-and-running with my app)

4. classes (I could potentially teach these if I ever get up-and-running.)

I took a slew of flask tutorials some years ago. None of the concepts are new. I'm an experienced web developer, but I haven't found my "happy home" in terms of a framework and starting point. I'm thinking this might be it, but would love more support. Are any of the ideas above--particularly the email list (or slack, though my preference is email list), and a place to call on gae-init-specific mentors--doable?

**Comment by bennyn** [comment]
👍 for videos!

**Comment by lipis** [comment]
I've been trying over the years to do something about those issues.. but the documentation it's always postponed for later! 

1. Yes we have a Slack channel and maybe it's not that obvious from the Readme since it's just a badge, so here is the direct link: https://gae-init-slack.herokuapp.com/
2. I never heard of codementor.io so I will check it out.
3. Videos.. Yes I've been trying to make something about it.. maybe one day :)
4. Depending on where you are, but from time to time I'm doing some hackathons.

Also, while some parts of [documentation](http://docs.gae-init.appspot.com) are outdated the [Quickstart](http://docs.gae-init.appspot.com/quickstart/),  [How To](http://docs.gae-init.appspot.com/howto/), [Requirements](http://docs.gae-init.appspot.com/requirement/) are not. So I think you can find some basic things on how to include Vue.js (maybe) in the how to part.. (BTW.. the documentation is also open source and if you notice an error or anything.. submitting an issues is the least you can do to help us).

Until we'll address these issues, please don't hesitate to ask questions as issues here or post them in our Slack channel if it's more specific.

**Comment by mroswell** [comment]
BTW, might be more work to have a person become specifically a codementor.io mentor, but would be great if there were a gae-init page listing folks who might be available to help folks over learning curves in a live one-on-one. Code-success-hungry customers could pay via Venmo/PayPal, even in the absence of a full-fledged codementor.io support system, and the pairs could get on Zoom or Hangouts, or telephone. (Though my guess is that folks populating this community would make terrific codementors, too, if someone wanted to go that route ( https://www.codementor.io/mentor/apply )
