### ISSUE TITLE
How do people normally manage version control?

### ISSUE THREAD

**Issue by JamsheedMistri** [gae-init/gae-init#883]
Hello there,

I'm new to gae-init and I was wondering what people normally do to get started with their own gae-init applciation. Do people normally make a fork and push to it? Or do people normally erase the history of gae-init's commits and start from scratch?

Either way, how do people pull updates if some of their code may conflict?

Thanks so much!

**Comment by lipis** [comment]
The best way is to fork it (to keep the history) and from time to time pull the updates.. if you are doing it often there shouldn't be many conflicts because usually the core is not changing that much, but of course there might be cases that that there are conflicts.. and the version number will indicate that.

https://github.com/gae-init/gae-init/releases

**Comment by JamsheedMistri** [comment]
Thank you very much!!
